// <auto-generated />
namespace DVD_rent.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class changemovie : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changemovie));
        
        string IMigrationMetadata.Id
        {
            get { return "202504071031558_change movie"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
